<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AnalysisLevel>latest</AnalysisLevel>
    <ApplicationIcon>Assets\ModernFormatConverter.ico</ApplicationIcon>
    <ApplicationManifest>ModernFormatConverter.manifest</ApplicationManifest>
    <AssemblyName>ModernFormatConverter</AssemblyName>
    <CheckForOverflowUnderflow>false</CheckForOverflowUnderflow>
    <CustomAfterMicrosoftCommonTargets>$(SolutionDir)Configuration\XamlCompiler.targets</CustomAfterMicrosoftCommonTargets>
    <DefaultLanguage>en-US</DefaultLanguage>
    <DefaultXamlRuntime>WinUI</DefaultXamlRuntime>
    <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    <Deterministic>true</Deterministic>
    <DesktopCompatible>true</DesktopCompatible>
    <DisableXbfLineInfo>false</DisableXbfLineInfo>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <EnablePriGenTooling>true</EnablePriGenTooling>
    <EnableTypeInfoReflection>false</EnableTypeInfoReflection>
    <_EnableWindowsDesktopGlobbing>true</_EnableWindowsDesktopGlobbing>
    <_EnableWindowsDesktopNETFrameworkImplicitReference>true</_EnableWindowsDesktopNETFrameworkImplicitReference>
    <ImportWindowsDesktopTargets>false</ImportWindowsDesktopTargets>
    <ImportFrameworkWinFXTargets>false</ImportFrameworkWinFXTargets>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <IncludeSymbols>false</IncludeSymbols>
    <LangVersion>latest</LangVersion>
    <Optimize>false</Optimize>
    <OutputType>WinExe</OutputType>
    <Platforms>x64;ARM64</Platforms>
    <ResolveComReferenceSilent>true</ResolveComReferenceSilent>
    <RootNamespace>ModernFormatConverter</RootNamespace>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <TargetFramework>net481</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <TargetPlatformVersion>10.0.26100.0</TargetPlatformVersion>
    <TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
    <UsingMicrosoftNETSdk>false</UsingMicrosoftNETSdk>
    <WindowsAppSDKBackgroundTask>false</WindowsAppSDKBackgroundTask>
    <WindowsAppSDKDeploymentManagerInitialize>false</WindowsAppSDKDeploymentManagerInitialize>
    <WindowsAppSDKSingleFileVerifyConfiguration>false</WindowsAppSDKSingleFileVerifyConfiguration>
    <WindowsAppSDKVerifyCsWinRtVersions>false</WindowsAppSDKVerifyCsWinRtVersions>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Platform)'=='x64'">
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Platform)'=='ARM64'">
    <RuntimeIdentifier>win-arm64</RuntimeIdentifier>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DebuggerSupport>true</DebuggerSupport>
    <DebugType>pdbonly</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebuggerSupport>false</DebuggerSupport>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="MainApp.xaml" />

    <Compile Update="Strings\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>

    <COMReference Include="IWshRuntimeLibrary">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>f935dc20-1cf0-11d0-adb9-00c04fd58a0b</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>

    <Content Include="Assets\ControlIcon\AudioConversion.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\ControlIcon\ConversionTools.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\ControlIcon\CustomCommand.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\ControlIcon\CutAudio.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\ControlIcon\FileInformation.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\ControlIcon\HATest.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\ControlIcon\Home.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\ControlIcon\OtherTools.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\ControlIcon\PhotoConversion.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\ControlIcon\Settings.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\ControlIcon\TaskManager.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\ControlIcon\VideoConversion.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Cover.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\LargeTile.scale-100.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\LargeTile.scale-125.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\LargeTile.scale-150.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\LargeTile.scale-200.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\LargeTile.scale-400.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Resources\HATest.mp4" CopyToOutputDirectory="Always" />
    <Content Include="Assets\SmallTile.scale-100.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\SmallTile.scale-125.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\SmallTile.scale-150.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\SmallTile.scale-200.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\SmallTile.scale-400.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\SplashScreen.scale-100.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\SplashScreen.scale-125.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\SplashScreen.scale-150.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\SplashScreen.scale-200.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\SplashScreen.scale-400.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.altform-lightunplated_targetsize-16.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.altform-lightunplated_targetsize-24.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.altform-lightunplated_targetsize-256.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.altform-lightunplated_targetsize-32.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.altform-lightunplated_targetsize-48.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.altform-unplated_targetsize-16.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.altform-unplated_targetsize-24.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.altform-unplated_targetsize-256.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.altform-unplated_targetsize-32.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.altform-unplated_targetsize-48.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.scale-100.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.scale-125.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.scale-150.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.scale-400.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.targetsize-16.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.targetsize-24.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.targetsize-256.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.targetsize-32.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square44x44Logo.targetsize-48.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square150x150Logo.scale-100.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square150x150Logo.scale-125.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square150x150Logo.scale-150.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Square150x150Logo.scale-400.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\StoreLogo.scale-100.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\StoreLogo.scale-125.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\StoreLogo.scale-150.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\StoreLogo.scale-200.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\StoreLogo.scale-400.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Wide310x150Logo.scale-100.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Wide310x150Logo.scale-125.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Wide310x150Logo.scale-150.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" CopyToOutputDirectory="Always" />
    <Content Include="Assets\Wide310x150Logo.scale-400.png" CopyToOutputDirectory="Always" />
    <Content Include="$(ProjectDir)\Tools\$(Platform)\avcodec-62.dll" Link="avcodec-62.dll" CopyToOutputDirectory="Always" />
    <Content Include="$(ProjectDir)\Tools\$(Platform)\avdevice-62.dll" Link="avdevice-62.dll" CopyToOutputDirectory="Always" />
    <Content Include="$(ProjectDir)\Tools\$(Platform)\avfilter-11.dll" Link="avfilter-11.dll" CopyToOutputDirectory="Always" />
    <Content Include="$(ProjectDir)\Tools\$(Platform)\avformat-62.dll" Link="avformat-62.dll" CopyToOutputDirectory="Always" />
    <Content Include="$(ProjectDir)\Tools\$(Platform)\avutil-60.dll" Link="avutil-60.dll" CopyToOutputDirectory="Always" />
    <Content Include="$(ProjectDir)\Tools\$(Platform)\ffmpeg.exe" Link="ffmpeg.exe" CopyToOutputDirectory="Always" />
    <Content Include="$(ProjectDir)\Tools\$(Platform)\FFmpegInterop.winmd" Link="FFmpegInterop.winmd" CopyToOutputDirectory="Always" />
    <Content Include="$(ProjectDir)\Tools\$(Platform)\FFmpegInterop.dll" Link="FFmpegInterop.dll" CopyToOutputDirectory="Always" />
    <Content Include="$(ProjectDir)\Tools\$(Platform)\MediaInfo.dll" Link="MediaInfo.dll" CopyToOutputDirectory="Always" />
    <Content Include="$(ProjectDir)\Tools\$(Platform)\swresample-6.dll" Link="swresample-6.dll" CopyToOutputDirectory="Always" />
    <Content Include="$(ProjectDir)\Tools\$(Platform)\swscale-9.dll" Link="swscale-9.dll" CopyToOutputDirectory="Always" />
    
    <EmbeddedResource Include="Strings\AppInformation.en-us.restext" />
    <EmbeddedResource Include="Strings\AppInformation.restext" />
    <EmbeddedResource Include="Strings\AppInformation.zh-hans.restext" />
    <EmbeddedResource Include="Strings\AudioConversion.en-us.restext" />
    <EmbeddedResource Include="Strings\AudioConversion.restext" />
    <EmbeddedResource Include="Strings\AudioConversion.zh-hans.restext" />
    <EmbeddedResource Include="Strings\AudioConversionOutputConfiguration.en-us.restext" />
    <EmbeddedResource Include="Strings\AudioConversionOutputConfiguration.restext" />
    <EmbeddedResource Include="Strings\AudioConversionOutputConfiguration.zh-hans.restext" />
    <EmbeddedResource Include="Strings\AudioEdit.en-us.restext" />
    <EmbeddedResource Include="Strings\AudioEdit.restext" />
    <EmbeddedResource Include="Strings\AudioEdit.zh-hans.restext" />
    <EmbeddedResource Include="Strings\AudioList.en-us.restext" />
    <EmbeddedResource Include="Strings\AudioList.restext" />
    <EmbeddedResource Include="Strings\AudioList.zh-hans.restext" />
    <EmbeddedResource Include="Strings\ConversionTools.en-us.restext" />
    <EmbeddedResource Include="Strings\ConversionTools.restext" />
    <EmbeddedResource Include="Strings\ConversionTools.zh-hans.restext" />
    <EmbeddedResource Include="Strings\CustomCommand.en-us.restext" />
    <EmbeddedResource Include="Strings\CustomCommand.restext" />
    <EmbeddedResource Include="Strings\CustomCommand.zh-hans.restext" />
    <EmbeddedResource Include="Strings\FileInformation.en-us.restext" />
    <EmbeddedResource Include="Strings\FileInformation.restext" />
    <EmbeddedResource Include="Strings\FileInformation.zh-hans.restext" />
    <EmbeddedResource Include="Strings\HATest.en-us.restext" />
    <EmbeddedResource Include="Strings\HATest.restext" />
    <EmbeddedResource Include="Strings\HATest.zh-hans.restext" />
    <EmbeddedResource Include="Strings\Home.en-us.restext" />
    <EmbeddedResource Include="Strings\Home.restext" />
    <EmbeddedResource Include="Strings\Home.zh-hans.restext" />
    <EmbeddedResource Include="Strings\License.en-us.restext" />
    <EmbeddedResource Include="Strings\License.restext" />
    <EmbeddedResource Include="Strings\License.zh-hans.restext" />
    <EmbeddedResource Include="Strings\NotificationTip.en-us.restext" />
    <EmbeddedResource Include="Strings\NotificationTip.restext" />
    <EmbeddedResource Include="Strings\NotificationTip.zh-hans.restext" />
    <EmbeddedResource Include="Strings\PhotoConversion.en-us.restext" />
    <EmbeddedResource Include="Strings\PhotoConversion.restext" />
    <EmbeddedResource Include="Strings\PhotoConversion.zh-hans.restext" />
    <EmbeddedResource Include="Strings\PhotoConversionOutputConfiguration.en-us.restext" />
    <EmbeddedResource Include="Strings\PhotoConversionOutputConfiguration.restext" />
    <EmbeddedResource Include="Strings\PhotoConversionOutputConfiguration.zh-hans.restext" />
    <EmbeddedResource Include="Strings\Resources.resx" Generator="PublicResXFileCodeGenerator" LastGenOutput="Resources.Designer.cs" />
    <EmbeddedResource Include="Strings\RestartApps.en-us.restext" />
    <EmbeddedResource Include="Strings\RestartApps.restext" />
    <EmbeddedResource Include="Strings\RestartApps.zh-hans.restext" />
    <EmbeddedResource Include="Strings\Settings.en-us.restext" />
    <EmbeddedResource Include="Strings\Settings.restext" />
    <EmbeddedResource Include="Strings\Settings.zh-hans.restext" />
    <EmbeddedResource Include="Strings\SettingsAbout.en-us.restext" />
    <EmbeddedResource Include="Strings\SettingsAbout.restext" />
    <EmbeddedResource Include="Strings\SettingsAbout.zh-hans.restext" />
    <EmbeddedResource Include="Strings\SettingsAdvanced.en-us.restext" />
    <EmbeddedResource Include="Strings\SettingsAdvanced.restext" />
    <EmbeddedResource Include="Strings\SettingsAdvanced.zh-hans.restext" />
    <EmbeddedResource Include="Strings\SettingsGeneral.en-us.restext" />
    <EmbeddedResource Include="Strings\SettingsGeneral.restext" />
    <EmbeddedResource Include="Strings\SettingsGeneral.zh-hans.restext" />
    <EmbeddedResource Include="Strings\TaskManager.en-us.restext" />
    <EmbeddedResource Include="Strings\TaskManager.restext" />
    <EmbeddedResource Include="Strings\TaskManager.zh-hans.restext" />
    <EmbeddedResource Include="Strings\TextToAudioOutputConfiguration.en-us.restext" />
    <EmbeddedResource Include="Strings\TextToAudioOutputConfiguration.restext" />
    <EmbeddedResource Include="Strings\TextToAudioOutputConfiguration.zh-hans.restext" />
    <EmbeddedResource Include="Strings\UpdateApp.en-us.restext" />
    <EmbeddedResource Include="Strings\UpdateApp.restext" />
    <EmbeddedResource Include="Strings\UpdateApp.zh-hans.restext" />
    <EmbeddedResource Include="Strings\VideoConversion.en-us.restext" />
    <EmbeddedResource Include="Strings\VideoConversion.restext" />
    <EmbeddedResource Include="Strings\VideoConversion.zh-hans.restext" />
    <EmbeddedResource Include="Strings\VideoConversionOutputConfiguration.en-us.restext" />
    <EmbeddedResource Include="Strings\VideoConversionOutputConfiguration.restext" />
    <EmbeddedResource Include="Strings\VideoConversionOutputConfiguration.zh-hans.restext" />
    <EmbeddedResource Include="Strings\VideoEdit.en-us.restext" />
    <EmbeddedResource Include="Strings\VideoEdit.restext" />
    <EmbeddedResource Include="Strings\VideoEdit.zh-hans.restext" />
    <EmbeddedResource Include="Strings\VideoList.en-us.restext" />
    <EmbeddedResource Include="Strings\VideoList.restext" />
    <EmbeddedResource Include="Strings\VideoList.zh-hans.restext" />
    <EmbeddedResource Include="Strings\VideoExportPictureOutputConfiguration.en-us.restext" />
    <EmbeddedResource Include="Strings\VideoExportPictureOutputConfiguration.restext" />
    <EmbeddedResource Include="Strings\VideoExportPictureOutputConfiguration.zh-hans.restext" />
    <EmbeddedResource Include="Strings\Window.en-us.restext" />
    <EmbeddedResource Include="Strings\Window.restext" />
    <EmbeddedResource Include="Strings\Window.zh-hans.restext" />

    <None Remove="MainApp.xaml" />
    <None Remove="Styles\AppBarButton.xaml" />
    <None Remove="Styles\ColorPicker.xaml" />
    <None Remove="Styles\ComboBox.xaml" />
    <None Remove="Styles\ImageCropper.xaml" />
    <None Remove="Styles\MediaPlayerElement.xaml" />
    <None Remove="Styles\NavigationView.xaml" />
    <None Remove="Styles\NumberBox.xaml" />
    <None Remove="Styles\TextBox.xaml" />
    <None Remove="Styles\ToggleSwitch.xaml" />
    <None Remove="Views\Dialogs\AppInformationDialog.xaml" />
    <None Remove="Views\Dialogs\LicenseDialog.xaml" />
    <None Remove="Views\Dialogs\RestartAppsDialog.xaml" />
    <None Remove="Views\Dialogs\UpdateAppDialog.xaml" />
    <None Remove="Views\NotificationTips\CopyPasteNotificationTip.xaml" />
    <None Remove="Views\NotificationTips\OperationResultNotificationTip.xaml" />
    <None Remove="Views\Pages\AudioConversionOutputConfigurationPage.xaml" />
    <None Remove="Views\Pages\AudioConversionPage.xaml" />
    <None Remove="Views\Pages\AudioEditPage.xaml" />
    <None Remove="Views\Pages\AudioListPage.xaml" />
    <None Remove="Views\Pages\CustomCommandPage.xaml" />
    <None Remove="Views\Pages\FileInformationPage.xaml" />
    <None Remove="Views\Pages\HATestPage.xaml" />
    <None Remove="Views\Pages\HomePage.xaml" />
    <None Remove="Views\Pages\PhotoConversionPage.xaml" />
    <None Remove="Views\Pages\SettingsAboutPage.xaml" />
    <None Remove="Views\Pages\SettingsAdvancedPage.xaml" />
    <None Remove="Views\Pages\SettingsGeneralPage.xaml" />
    <None Remove="Views\Pages\SettingsPage.xaml" />
    <None Remove="Views\Pages\TaskManagerPage.xaml" />
    <None Remove="Views\Pages\TextToAudioOutputConfigurationPage.xaml" />
    <None Remove="Views\Pages\VideoConversionOutputConfigurationPage.xaml" />
    <None Remove="Views\Pages\VideoConversionPage.xaml" />
    <None Remove="Views\Pages\VideoEditPage.xaml" />
    <None Remove="Views\Pages\VideoExportPictureOutputConfigurationPage.xaml" />
    <None Remove="Views\Pages\VideoListPage.xaml" />
    <None Remove="Views\Windows\ConversionToolsWindow.xaml" />
    <None Remove="Views\Windows\MainWindow.xaml" />
    <None Remove="Views\Windows\PhotoConversionOutputConfigurationWindow.xaml" />
    
    <Page Include="Styles\AppBarButton.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Styles\ColorPicker.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Styles\ComboBox.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Styles\ImageCropper.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Styles\MediaPlayerElement.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Styles\NavigationView.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Styles\NumberBox.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Styles\TextBox.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Styles\ToggleSwitch.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Dialogs\AppInformationDialog.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Dialogs\LicenseDialog.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Dialogs\RestartAppsDialog.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Dialogs\UpdateAppDialog.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\NotificationTips\CopyPasteNotificationTip.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\NotificationTips\OperationResultNotificationTip.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\AudioConversionOutputConfigurationPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\AudioConversionPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\AudioEditPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\AudioListPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\CustomCommandPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\FileInformationPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\HATestPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\HomePage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\PhotoConversionPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\SettingsAboutPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\SettingsAdvancedPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\SettingsGeneralPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\SettingsPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\TaskManagerPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\TextToAudioOutputConfigurationPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\VideoConversionOutputConfigurationPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\VideoConversionPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\VideoEditPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\VideoExportPictureOutputConfigurationPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Pages\VideoListPage.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Windows\ConversionToolsWindow.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Windows\MainWindow.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    <Page Include="Views\Windows\PhotoConversionOutputConfigurationWindow.xaml" XamlRuntime="$(DefaultXamlRuntime)" />
    
    <PRIResource Include="Strings\en-us\Resources.resjson" />
		<PRIResource Include="Strings\zh-hans\Resources.resjson" />
    
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1839" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools.MSIX" Version="1.7.260518100" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
    <PackageReference Include="Microsoft.Windows.SDK.NET.Ref" Version="10.0.26100.84" PrivateAssets="none" IncludeAssets="none" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.WindowsAppSDK.Base" Version="2.0.4" />
    <PackageReference Include="Microsoft.WindowsAppSDK.Foundation" Version="2.0.21" />
    <PackageReference Include="Microsoft.WindowsAppSDK.InteractiveExperiences" Version="2.0.13" GeneratePathProperty="True" />
    <PackageReference Include="Microsoft.WindowsAppSDK.Runtime" Version="2.1.3" />
    <PackageReference Include="Microsoft.WindowsAppSDK.WinUI" Version="2.1.0" GeneratePathProperty="True" IncludeAssets="none" PrivateAssets="all" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.6.1" />
    <PackageReference Include="System.Runtime.WindowsRuntime" Version="4.7.0" />

    <Reference Include="$(PkgMicrosoft_WindowsAppSDK_InteractiveExperiences)\metadata\10.0.18362.0\Microsoft.UI.winmd" Private="false" Visible="false" />
    <Reference Include="$(PkgMicrosoft_WindowsAppSDK_WinUI)\metadata\Microsoft.UI.Text.winmd" Private="false" Visible="false" />
    <Reference Include="$(PkgMicrosoft_WindowsAppSDK_WinUI)\metadata\Microsoft.UI.Xaml.winmd" Private="false" Visible="false" />
    <Reference Include="$(PkgMicrosoft_Windows_SDK_NET_Ref)\winmd\*.winmd" Private="false" Visible="false" />
    <Reference Include="$(WindowsSdkPath)\UnionMetadata\Facade\Windows.WinMD" Private="false" Visible="false" />
    <Reference Include="$(ProjectDir)Tools\$(Platform)\FFmpegInterop.winmd" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Speech" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>
